extends Node

const CONNECTOR_DISABLED := -1
const CONNECTOR_TIMESTAMP := 0
const CONNECTOR_AUDIOSTREAM := 1
const CONNECTOR_SIGNAL := 2
const CONNECTOR_DISABLED_COLOUR := Color.TRANSPARENT
const CONNECTOR_TIMESTAMP_COLOUR := Color.WHITE
const CONNECTOR_AUDIOSTREAM_COLOUR := Color.BLUE
const CONNECTOR_SIGNAL_COLOUR := Color.GREEN


